Add feature/pg branch again
alex-ismailov/TaskManager pull request #3
Opened 2021-12-05 09:44 UTC by alex-ismailov

Last time I made a mistake and started the feature/pg branch from feature/docker-compose, so I created it again from the main branch and made a new PR.

2021-12-06 08:15 UTC, greybutton requested changes
1 нет, необходимых изменений из урока
2 В TaskManager нужно использовать git-flow. Cоздать ветку develop, и от нее создавать ветки с кодом и в нее же сливать. develop — основная ветка разработки. Подробнее описано тут: https://learn.dualboot.ru/courses/5/lessons/73/practices/1064

2021-12-19 19:00 UTC, alex-ismailov commented
Заново создал ветку feature/pg и сделал пуш форсом (git push --all -f)

2021-12-20 16:11 UTC, greybutton requested changes
не хватает схемы и изменений в docker-compose.yml

2021-12-20 22:21 UTC, alex-ismailov commented
@greybutton, можно чуть подробнее? Проверил файлы `schema.rb` и `docker-compose.yml` и их содержание соответствует предыдущим двум урокам. Не понимаю как надо правильно сделать?

2021-12-21 15:46 UTC, greybutton commented
в мердже реквесте нет изменений файлов schema.rb (этот вроде только здесь первый раз генерирутся) и docker-compose.yml. Предыдущим урокам соответствует, уроку Добавить в проект PostgreSQL, нет

например секции
```
environment:
  DATABASE_HOST: db
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
```

2021-12-26 16:39 UTC, alex-ismailov commented
@greybutton, удалил файл `db/schema.rb`. Еще раз добавил переменные окружения
`DATABASE_HOST: db
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres`
 в 
 `docker-compose.yml`. 
 заново сделал setup базы.

2021-12-27 15:26 UTC, greybutton commented
отправь на проверку на сайте обучения

2021-12-28 14:26 UTC, greybutton approved these changes

2022-05-17 10:26 UTC, merged